# Generated by Django 5.2.6 on 2025-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color_scheme',
            field=models.CharField(default='colored', max_length=50),
        ),
    ]
