# Generated by Django 5.2.6 on 2025-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_default_prompt_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='final_prompt',
            field=models.TextField(blank=True, help_text='Custom final prompt to use for generation (overrides auto-generated prompt)', null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='use_custom_prompt',
            field=models.BooleanField(default=False, help_text='Whether to use the custom final prompt instead of auto-generating'),
        ),
    ]
