# Generated by Django 5.2.6 on 2025-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_scene_final_prompt_scene_use_custom_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_model',
            field=models.CharField(choices=[('google_nano_banana', 'Google Nano Banana'), ('stability_ai', 'Stability AI'), ('seedream', 'Seedream 4')], default='google_nano_banana', help_text='AI model to use for image generation', max_length=50),
        ),
    ]
