# Generated by Django 5.2.6 on 2025-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_update_seedream_model_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='generated_image',
            field=models.ImageField(blank=True, help_text='AI-generated image of the character', null=True, upload_to='character_images/'),
        ),
        migrations.AddField(
            model_name='character',
            name='generation_prompt',
            field=models.TextField(blank=True, help_text="The prompt used to generate this character's image", null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Reference image for character consistency', null=True, upload_to='character_references/'),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
