# Generated by Django 5.2.6 on 2025-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_character_generated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='characters',
            field=models.ManyToManyField(blank=True, help_text='Characters that appear in this scene', related_name='scenes', to='stories.character'),
        ),
    ]
