# Generated by Django 5.2.6 on 2025-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_scene_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='edit_mode',
            field=models.BooleanField(default=False, help_text='Whether to edit existing image instead of generating new one'),
        ),
        migrations.AddField(
            model_name='scene',
            name='edit_prompt',
            field=models.TextField(blank=True, help_text="Instructions for editing the existing image (e.g., 'Make it sunset', 'Add rain')", null=True),
        ),
    ]
