# Generated by Django 5.2.6 on 2025-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_scene_edit_mode_scene_edit_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='edit_mode',
        ),
        migrations.AlterField(
            model_name='scene',
            name='edit_prompt',
            field=models.TextField(blank=True, help_text="Last edit instructions used (e.g., 'Make it sunset', 'Add rain')", null=True),
        ),
    ]
