# Generated by Django 5.2.6 on 2025-09-22 12:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_update_template_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_generation', models.DecimalField(decimal_places=4, default=Decimal('0.0390'), help_text='Cost per image generation (default: $0.039 for Gemini 2.5 Flash Image)', max_digits=10)),
                ('cost_per_edit', models.DecimalField(decimal_places=4, default=Decimal('0.0390'), help_text='Cost per image edit (default: $0.039 for Gemini 2.5 Flash Image)', max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', help_text='Currency for cost tracking', max_length=3)),
                ('is_tracking_enabled', models.BooleanField(default=True, help_text='Enable/disable cost tracking')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generation Settings',
                'verbose_name_plural': 'Generation Settings',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='generation_count',
            field=models.IntegerField(default=0, help_text='Total number of image generations for this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_generation_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total cost of all image generations for this project', max_digits=10),
        ),
        migrations.CreateModel(
            name='GenerationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('new', 'New Generation'), ('edit', 'Edit'), ('character', 'Character Generation')], help_text='Type of generation', max_length=20)),
                ('cost', models.DecimalField(decimal_places=4, help_text='Cost of this generation', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency used for this cost', max_length=3)),
                ('prompt_preview', models.TextField(blank=True, help_text='Preview of the prompt used (first 200 chars)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_costs', to='stories.character')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_costs', to='stories.project')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_costs', to='stories.scene')),
            ],
            options={
                'verbose_name': 'Generation Cost',
                'verbose_name_plural': 'Generation Costs',
                'ordering': ['-created_at'],
            },
        ),
    ]
