# Generated by Django 5.2.6 on 2025-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_generationsettings_project_generation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsettings',
            name='google_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Gemini API key (overrides environment variable if set)', max_length=255),
        ),
        migrations.AddField(
            model_name='generationsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='OpenAI API key (overrides environment variable if set)', max_length=255),
        ),
    ]
